# SCB0 is the console UART on this board; it is repurposed as SPI slave
# here, so no UART/console is available in this sample.
CONFIG_SPI=y
CONFIG_SPI_SLAVE=y
CONFIG_GPIO=y

CONFIG_MAIN_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=768